### ISSUE TITLE
unclear error message when connection refused (..undefined..)

### ISSUE THREAD

**Issue by jakopako** [jakopako/graph-nessus#1]
Error: Provider authentication failed at undefined: undefined Failed to authenticate with the nessus API: undefined
      at APIClient.verifyAuthentication (/jupiterone/graph-nessus/src/client.ts:36:13)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at Object.validateInvocation (/jupiterone/graph-nessus/src/config.ts:80:3)
      at executeWithContext (/jupiterone/graph-nessus/node_modules/@jupiterone/integration-sdk-cli/node_modules/@jupiterone/integration-sdk-runtime/src/execution/executeIntegration.ts:183:7)
      at timeOperation (/jupiterone/graph-nessus/node_modules/@jupiterone/integration-sdk-cli/node_modules/@jupiterone/integration-sdk-runtime/src/metrics/index.ts:16:10)
      at executeIntegrationLocally (/jupiterone/graph-nessus/node_modules/@jupiterone/integration-sdk-cli/node_modules/@jupiterone/integration-sdk-runtime/src/execution/executeIntegration.ts:80:18)
      at Command.<anonymous> (/jupiterone/graph-nessus/node_modules/@jupiterone/integration-sdk-cli/src/commands/collect.ts:87:23)
      at async Promise.all (index 0)
  Caused By: FetchError: request to https://bla:8843/session failed, reason: connect ECONNREFUSED bla:8843
      at ClientRequest.<anonymous> (/jupiterone/graph-nessus/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (events.js:400:28)
      at ClientRequest.emit (domain.js:475:12)
      at TLSSocket.socketErrorListener (_http_client.js:475:9)
      at TLSSocket.emit (events.js:400:28)
      at TLSSocket.emit (domain.js:475:12)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by jakopako** [comment]
look at graph-orion for comparison
